### ISSUE TITLE
01_Obfuscation.ps1 causes windows defender antivirus malware alert

### ISSUE THREAD

**Issue by ascarter** [PacktPublishing/Learn-PowerShell-Core-6.0#4]
I cloned the repo to my machine and Windows Defender raised a malware alert for this file:

https://github.com/PacktPublishing/Learn-PowerShell-Core-6.0/blob/master/Chapter07/05_Obfuscation/01_Obfuscation.ps1

![image](https://user-images.githubusercontent.com/4931/71632145-cad72000-2bc1-11ea-9147-c302d22aaebe.png)

**Comment by ddneves** [comment]
Hi Andrew,

I added some comments to the code to show the hidden and obfuscated code that would be executed.

I cross-checked with my W10 device and can confirm that I am now getting the same errors. 

Unfortunately, this is a false positive created by the obfuscation itself. 

I attached the execution results:
![Anmerkung 2020-08-05 082915](https://user-images.githubusercontent.com/13232517/89416553-b77acd00-d72d-11ea-82d7-f258cd1921bb.png)

Cheers.
